/* automatically generated by rust-bindgen 0.60.1 */
//!
//! Bindgen generated bindings
//!
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(improper_ctypes)]
#![allow(clippy::upper_case_acronyms)]
#![allow(clippy::redundant_static_lifetimes)]

use libxml::bindings::xmlChar;
use libxml::bindings::xmlDocPtr;
use libxml::bindings::xmlExternalEntityLoader;
use libxml::bindings::xmlNodePtr;
use libxml::bindings::xmlNodeSetPtr;
use libxml::bindings::xmlOutputBufferPtr;
use libxml::bindings::xmlParserInputBufferPtr;

#[cfg(feature = "bindgen")]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(all(not(feature = "bindgen"), target_os = "windows"))]
include!("default_bindings_win32.rs");

#[cfg(all(not(feature = "bindgen"), not(target_os = "windows")))]
include!("default_bindings.rs");
